авыавыаы

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,15 +7,29 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Install the latest version of uv
         uses: astral-sh/setup-uv@v6
 
-      - name: tests
-        run: uv run pytest
+      - name: Run tests and save output
+        id: pytest
+        run: |
+
+           uv run pytest -v >> test_result.txt
+          # TEST_OUTPUT=$(uv run pytest -v || true)
+          
+          # echo "test_output<<EOF" >> $GITHUB_OUTPUT
+          # echo "$TEST_OUTPUT" >> $GITHUB_OUTPUT
+          # echo "EOF" >> $GITHUB_OUTPUT
+          
+          # # Check if tests failed
+          # if echo "$TEST_OUTPUT" | grep -q "FAILED"; then
+          #   echo "has_failures=true" >> $GITHUB_OUTPUT
+          # else
+          #   echo "has_failures=false" >> $GITHUB_OUTPUT
+          # fi
 
       - name: send telegram message on push
         if: always()
@@ -23,14 +37,7 @@ jobs:
         with:
           to: ${{ secrets.TELEGRAM_TO }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
+          document: test_result.txt
           message: |
-
-            hi
-            # ${{ github.actor }} created commit:
-            # Commit message: ${{ github.event.commits[0].message }}
+            аваыва
             
-            # Repository: ${{ github.repository }}
-            
-            # See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-
-
